"""MacGear Rebate Master: registers, agreements, rates, evidence, the feed

Revision: 0001
Previous: 
Created: 2026-10-08 14:16:28.698883
"""

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'rebate_editor', 'rebate_reviewer', 'brand_approver', 'viewer', name='role', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('auth_method', sa.Enum('local', 'microsoft', name='auth_method', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("auth_method <> 'local' OR password_hash IS NOT NULL", name=op.f('ck_app_user_local_user_has_password')),
    sa.CheckConstraint("auth_method IN ('local', 'microsoft')", name=op.f('ck_app_user_auth_method')),
    sa.CheckConstraint("role IN ('admin', 'rebate_editor', 'rebate_reviewer', 'brand_approver', 'viewer')", name=op.f('ck_app_user_role')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_app_user_email_is_lower_case')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_app_user_created_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('netsuite_class_id', sa.Integer(), nullable=True),
    sa.Column('is_brand', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('forecast_tier', sa.Enum('strategic', 'tail', 'pre_revenue', name='forecast_tier', native_enum=False, create_constraint=False, length=32), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('is_inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("forecast_tier IN ('strategic', 'tail', 'pre_revenue')", name=op.f('ck_brand_forecast_tier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand')),
    sa.UniqueConstraint('code', name=op.f('uq_brand_code')),
    sa.UniqueConstraint('netsuite_class_id', name=op.f('uq_brand_netsuite_class_id'))
    )
    op.create_table('customer_group',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_intercompany', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_customer_group')),
    sa.UniqueConstraint('name', name=op.f('uq_customer_group_name'))
    )
    op.create_table('entity',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('netsuite_subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('functional_currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_entity')),
    sa.UniqueConstraint('netsuite_subsidiary_id', name=op.f('uq_entity_netsuite_subsidiary_id'))
    )
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_api_token_created_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_token_token_hash'))
    )
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_event_actor_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netsuite_customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_code', sa.String(length=8), nullable=False),
    sa.Column('customer_group_code', sa.String(length=16), nullable=True),
    sa.Column('netsuite_entity_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('category', sa.String(length=100), server_default='', nullable=False),
    sa.Column('parent_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('terms', sa.String(length=50), server_default='', nullable=False),
    sa.Column('is_inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['customer_group_code'], ['customer_group.code'], name=op.f('fk_customer_customer_group_code_customer_group')),
    sa.ForeignKeyConstraint(['entity_code'], ['entity.code'], name=op.f('fk_customer_entity_code_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('netsuite_customer_id', name=op.f('uq_customer_netsuite_customer_id'))
    )
    op.create_table('load_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('customers', 'classes', 'rebate_workbook', 'forecasting_import', name='load_kind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('entity_code', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('loaded_by_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.CheckConstraint("kind IN ('customers', 'classes', 'rebate_workbook', 'forecasting_import')", name=op.f('ck_load_batch_load_kind')),
    sa.ForeignKeyConstraint(['entity_code'], ['entity.code'], name=op.f('fk_load_batch_entity_code_entity')),
    sa.ForeignKeyConstraint(['loaded_by_id'], ['app_user.id'], name=op.f('fk_load_batch_loaded_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_batch')),
    sa.UniqueConstraint('kind', 'entity_code', 'file_sha256', name='uq_load_batch_kind_entity_file')
    )
    op.create_table('rebate_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('entity_code', sa.String(length=8), nullable=False),
    sa.Column('customer_label', sa.String(length=200), nullable=False),
    sa.Column('customer_group_code', sa.String(length=16), nullable=True),
    sa.Column('brand_code', sa.String(length=64), nullable=True),
    sa.Column('product_scope', sa.String(length=300), nullable=False),
    sa.Column('rate_type', sa.Enum('rebate', 'mdf', 'damage', 'settlement', 'co_op', name='rate_type', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('basis', sa.Enum('rebate_eligible_sales', 'gross_revenue', name='rebate_basis', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('accrual_mode', sa.Enum('accrue', 'check_only', name='accrual_mode', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('agreed_by', sa.String(length=200), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("accrual_mode IN ('accrue', 'check_only')", name=op.f('ck_rebate_agreement_accrual_mode')),
    sa.CheckConstraint("basis IN ('rebate_eligible_sales', 'gross_revenue')", name=op.f('ck_rebate_agreement_rebate_basis')),
    sa.CheckConstraint("rate_type IN ('rebate', 'mdf', 'damage', 'settlement', 'co_op')", name=op.f('ck_rebate_agreement_rate_type')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_rebate_agreement_created_by_id_app_user')),
    sa.ForeignKeyConstraint(['customer_group_code'], ['customer_group.code'], name=op.f('fk_rebate_agreement_customer_group_code_customer_group')),
    sa.ForeignKeyConstraint(['entity_code'], ['entity.code'], name=op.f('fk_rebate_agreement_entity_code_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_agreement')),
    sa.UniqueConstraint('code', name=op.f('uq_rebate_agreement_code'))
    )
    op.create_table('rebate_approver_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_rebate_approver_scope_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_approver_scope')),
    sa.UniqueConstraint('user_id', 'brand_code', name='uq_rebate_approver_scope_user_brand')
    )
    op.create_table('rebate_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('band_from', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('band_to', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='review_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('load_flags', sa.JSON(), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("status = 'proposed' OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_rebate_rate_decision_records_reviewer')),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected')", name=op.f('ck_rebate_rate_review_status')),
    sa.CheckConstraint('band_from IS NULL OR band_to IS NULL OR band_to > band_from', name=op.f('ck_rebate_rate_band_in_order')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_rebate_rate_dates_in_order')),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_rebate_rate_reason_stated')),
    sa.CheckConstraint('length(trim(source_reference)) > 0', name=op.f('ck_rebate_rate_source_stated')),
    sa.CheckConstraint('rate >= 0 AND rate < 1', name=op.f('ck_rebate_rate_rate_is_a_fraction')),
    sa.CheckConstraint('reviewed_by_id IS NULL OR reviewed_by_id <> entered_by_id', name=op.f('ck_rebate_rate_four_eyes')),
    sa.ForeignKeyConstraint(['agreement_id'], ['rebate_agreement.id'], name=op.f('fk_rebate_rate_agreement_id_rebate_agreement')),
    sa.ForeignKeyConstraint(['entered_by_id'], ['app_user.id'], name=op.f('fk_rebate_rate_entered_by_id_app_user')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['app_user.id'], name=op.f('fk_rebate_rate_reviewed_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_rate'))
    )
    op.create_table('rebate_true_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='review_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected')", name=op.f('ck_rebate_true_up_review_status')),
    sa.CheckConstraint('extract(day from period) = 1', name=op.f('ck_rebate_true_up_period_is_first_of_month')),
    sa.CheckConstraint('reviewed_by_id IS NULL OR reviewed_by_id <> entered_by_id', name=op.f('ck_rebate_true_up_four_eyes')),
    sa.ForeignKeyConstraint(['agreement_id'], ['rebate_agreement.id'], name=op.f('fk_rebate_true_up_agreement_id_rebate_agreement')),
    sa.ForeignKeyConstraint(['entered_by_id'], ['app_user.id'], name=op.f('fk_rebate_true_up_entered_by_id_app_user')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['app_user.id'], name=op.f('fk_rebate_true_up_reviewed_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_true_up'))
    )
    op.create_table('rebate_workbook_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('sales', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('rebate_due', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('extract(day from period) = 1', name=op.f('ck_rebate_workbook_month_period_is_first_of_month')),
    sa.ForeignKeyConstraint(['agreement_id'], ['rebate_agreement.id'], name=op.f('fk_rebate_workbook_month_agreement_id_rebate_agreement')),
    sa.ForeignKeyConstraint(['batch_id'], ['load_batch.id'], name=op.f('fk_rebate_workbook_month_batch_id_load_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_workbook_month')),
    sa.UniqueConstraint('agreement_id', 'period', name='uq_rebate_workbook_month_agreement_period')
    )
    op.create_table('evidence_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_evidence_file_not_empty')),
    sa.ForeignKeyConstraint(['agreement_id'], ['rebate_agreement.id'], name=op.f('fk_evidence_file_agreement_id_rebate_agreement')),
    sa.ForeignKeyConstraint(['rate_id'], ['rebate_rate.id'], name=op.f('fk_evidence_file_rate_id_rebate_rate')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['app_user.id'], name=op.f('fk_evidence_file_uploaded_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_file'))
    )
    # ### end Alembic commands ###

    # The audit log is append-only.
    op.execute(AUDIT_IS_APPEND_ONLY)
    op.execute("CREATE TRIGGER audit_event_append_only BEFORE UPDATE OR DELETE ON audit_event "
               "FOR EACH ROW EXECUTE FUNCTION mgrm_forbid_audit_change()")
    # Evidence is kept exactly as uploaded: never changed, never removed.
    op.execute(EVIDENCE_IS_PERMANENT)
    op.execute("CREATE TRIGGER evidence_file_permanent BEFORE UPDATE OR DELETE ON evidence_file "
               "FOR EACH ROW EXECUTE FUNCTION mgrm_forbid_evidence_change()")
    # Spec §4.5.1: once reviewed, a rate is history. Only an open-ended approved rate may be given an end date, once.
    op.execute(REVIEWED_RATE_IS_HISTORY)
    op.execute("CREATE TRIGGER rebate_rate_history BEFORE UPDATE OR DELETE ON rebate_rate "
               "FOR EACH ROW EXECUTE FUNCTION mgrm_guard_reviewed_rebate_rate()")

    # Reference data fixed by the business (spec §1.2, §4.3). Further groups are added in the platform.
    entity = sa.table('entity', sa.column('code'), sa.column('name'), sa.column('netsuite_subsidiary_id'), sa.column('functional_currency'))
    op.bulk_insert(entity, [
        {'code': 'MGAU', 'name': 'MacGear Australia', 'netsuite_subsidiary_id': 2, 'functional_currency': 'AUD'},
        {'code': 'MGNZ', 'name': 'MacGear New Zealand', 'netsuite_subsidiary_id': 3, 'functional_currency': 'NZD'},
    ])
    group = sa.table('customer_group', sa.column('code'), sa.column('name'), sa.column('is_intercompany'))
    op.bulk_insert(group, [
        {'code': 'HN', 'name': 'Harvey Norman', 'is_intercompany': False},
        {'code': 'JBH', 'name': 'JB Hi-Fi', 'is_intercompany': False},
        {'code': 'AMZ', 'name': 'Amazon', 'is_intercompany': False},
        {'code': 'NL', 'name': 'Noel Leeming', 'is_intercompany': False},
        {'code': 'OW', 'name': 'Officeworks', 'is_intercompany': False},
        {'code': 'TGG', 'name': 'The Good Guys', 'is_intercompany': False},
        {'code': 'PBT', 'name': 'PB Technology', 'is_intercompany': False},
        {'code': 'D2C', 'name': 'D2C', 'is_intercompany': False},
        {'code': 'IC', 'name': 'Intercompany', 'is_intercompany': True},
        {'code': 'OTHER', 'name': 'Other', 'is_intercompany': False},
    ])


AUDIT_IS_APPEND_ONLY = """
CREATE FUNCTION mgrm_forbid_audit_change() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN
    RAISE EXCEPTION 'The audit log is append-only; entries cannot be changed or removed.'
        USING ERRCODE = 'restrict_violation';
END
$body$
"""

EVIDENCE_IS_PERMANENT = """
CREATE FUNCTION mgrm_forbid_evidence_change() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN
    RAISE EXCEPTION 'Evidence is kept exactly as uploaded; it cannot be changed or removed. Attach a further file instead.'
        USING ERRCODE = 'restrict_violation';
END
$body$
"""

REVIEWED_RATE_IS_HISTORY = """
CREATE FUNCTION mgrm_guard_reviewed_rebate_rate() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'proposed' THEN
            RAISE EXCEPTION 'A reviewed rebate rate is part of the history and cannot be deleted.'
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'proposed' THEN
        RETURN NEW;
    END IF;
    IF (NEW.agreement_id, NEW.rate, NEW.effective_from, NEW.band_from, NEW.band_to, NEW.status,
        NEW.source_reference, NEW.reason, NEW.entered_by_id, NEW.entered_at, NEW.reviewed_by_id, NEW.reviewed_at)
       IS DISTINCT FROM
       (OLD.agreement_id, OLD.rate, OLD.effective_from, OLD.band_from, OLD.band_to, OLD.status,
        OLD.source_reference, OLD.reason, OLD.entered_by_id, OLD.entered_at, OLD.reviewed_by_id, OLD.reviewed_at) THEN
        RAISE EXCEPTION 'A reviewed rebate rate cannot be changed. Propose a new rate instead.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.effective_to IS DISTINCT FROM OLD.effective_to AND
       (OLD.status <> 'approved' OR OLD.effective_to IS NOT NULL OR NEW.effective_to IS NULL) THEN
        RAISE EXCEPTION 'Only an open-ended approved rate can be given an end date, and only once.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$body$
"""


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS rebate_rate_history ON rebate_rate")
    op.execute("DROP TRIGGER IF EXISTS evidence_file_permanent ON evidence_file")
    op.execute("DROP TRIGGER IF EXISTS audit_event_append_only ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS mgrm_guard_reviewed_rebate_rate()")
    op.execute("DROP FUNCTION IF EXISTS mgrm_forbid_evidence_change()")
    op.execute("DROP FUNCTION IF EXISTS mgrm_forbid_audit_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_file')
    op.drop_table('rebate_workbook_month')
    op.drop_table('rebate_true_up')
    op.drop_table('rebate_rate')
    op.drop_table('rebate_approver_scope')
    op.drop_table('rebate_agreement')
    op.drop_table('load_batch')
    op.drop_table('customer')
    op.drop_table('audit_event')
    op.drop_table('api_token')
    op.drop_table('entity')
    op.drop_table('customer_group')
    op.drop_table('brand')
    op.drop_table('app_user')
    # ### end Alembic commands ###
