"""Four eyes on every change: new agreements, agreement changes, ending, withdrawing; the combined role

Revision: 0002
Previous: 0001
Created: 2026-10-09 14:37:06.335487
"""

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebate_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('details', 'end', name='change_kind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'withdrawn', name='review_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('entered_by_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint("kind IN ('details', 'end')", name=op.f('ck_rebate_change_request_change_kind')),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected', 'withdrawn')", name=op.f('ck_rebate_change_request_review_status')),
    sa.CheckConstraint("status IN ('proposed', 'withdrawn') OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_rebate_change_request_decision_records_reviewer')),
    sa.CheckConstraint('length(trim(reason)) > 0', name=op.f('ck_rebate_change_request_reason_stated')),
    sa.CheckConstraint('reviewed_by_id IS NULL OR reviewed_by_id <> entered_by_id', name=op.f('ck_rebate_change_request_four_eyes')),
    sa.ForeignKeyConstraint(['agreement_id'], ['rebate_agreement.id'], name=op.f('fk_rebate_change_request_agreement_id_rebate_agreement')),
    sa.ForeignKeyConstraint(['entered_by_id'], ['app_user.id'], name=op.f('fk_rebate_change_request_entered_by_id_app_user')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['app_user.id'], name=op.f('fk_rebate_change_request_reviewed_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebate_change_request'))
    )
    op.add_column('evidence_file', sa.Column('change_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_evidence_file_change_request_id_rebate_change_request'), 'evidence_file', 'rebate_change_request', ['change_request_id'], ['id'])
    # ### end Alembic commands ###

    # The combined "Rebate editor and approver" role, and the "withdrawn" status.
    op.drop_constraint(op.f('ck_app_user_role'), 'app_user', type_='check')
    op.create_check_constraint(op.f('ck_app_user_role'), 'app_user', _in('role', ROLES))
    for table in ('rebate_rate', 'rebate_true_up'):
        op.drop_constraint(op.f(f'ck_{table}_review_status'), table, type_='check')
        op.create_check_constraint(op.f(f'ck_{table}_review_status'), table, _in('status', STATUSES))
    op.drop_constraint(op.f('ck_rebate_rate_decision_records_reviewer'), 'rebate_rate', type_='check')
    op.create_check_constraint(
        op.f('ck_rebate_rate_decision_records_reviewer'), 'rebate_rate',
        "status IN ('proposed', 'withdrawn') OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)",
    )
    # A reviewed or withdrawn change request is history: it cannot be changed or deleted.
    op.execute(DECIDED_CHANGE_IS_HISTORY)
    op.execute("CREATE TRIGGER rebate_change_request_history BEFORE UPDATE OR DELETE ON rebate_change_request "
               "FOR EACH ROW EXECUTE FUNCTION mgrm_guard_decided_change_request()")


ROLES = ('admin', 'rebate_maintainer', 'rebate_editor', 'rebate_reviewer', 'brand_approver', 'viewer')
PREVIOUS_ROLES = ('admin', 'rebate_editor', 'rebate_reviewer', 'brand_approver', 'viewer')
STATUSES = ('proposed', 'approved', 'rejected', 'withdrawn')
PREVIOUS_STATUSES = ('proposed', 'approved', 'rejected')

DECIDED_CHANGE_IS_HISTORY = """
CREATE FUNCTION mgrm_guard_decided_change_request() RETURNS trigger LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'DELETE' OR OLD.status <> 'proposed' THEN
        RAISE EXCEPTION 'A change request that has been decided or withdrawn is part of the history and cannot be changed or deleted.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF (NEW.agreement_id, NEW.kind, NEW.payload::text, NEW.reason, NEW.entered_by_id, NEW.entered_at)
       IS DISTINCT FROM (OLD.agreement_id, OLD.kind, OLD.payload::text, OLD.reason, OLD.entered_by_id, OLD.entered_at) THEN
        RAISE EXCEPTION 'A proposed change cannot be edited. Withdraw it and propose again.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$body$
"""


def _in(column: str, values) -> str:
    return f"{column} IN (" + ", ".join(f"'{v}'" for v in values) + ")"


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS rebate_change_request_history ON rebate_change_request")
    op.execute("DROP FUNCTION IF EXISTS mgrm_guard_decided_change_request()")
    op.drop_constraint(op.f('ck_rebate_rate_decision_records_reviewer'), 'rebate_rate', type_='check')
    op.create_check_constraint(op.f('ck_rebate_rate_decision_records_reviewer'), 'rebate_rate',
                               "status = 'proposed' OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)")
    for table in ('rebate_rate', 'rebate_true_up'):
        op.drop_constraint(op.f(f'ck_{table}_review_status'), table, type_='check')
        op.create_check_constraint(op.f(f'ck_{table}_review_status'), table, _in('status', PREVIOUS_STATUSES))
    op.drop_constraint(op.f('ck_app_user_role'), 'app_user', type_='check')
    op.create_check_constraint(op.f('ck_app_user_role'), 'app_user', _in('role', PREVIOUS_ROLES))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_file_change_request_id_rebate_change_request'), 'evidence_file', type_='foreignkey')
    op.drop_column('evidence_file', 'change_request_id')
    op.drop_table('rebate_change_request')
    # ### end Alembic commands ###
